### PR TITLE
Collapsible menu - first version

### PR DESCRIPTION
**Pull request by rreedtd**
First working version of collapsible sidebar menu elements.

I believe I have everything working with jQuery and bootstrap:

- Expand menus on button click
- Collapse menus on button click
- Automatically expand current and all parent menus based on current page / navigation

Can you run this branch / take a look in other browsers, while also considering the styling? Does this look good? 
This change is in anticipation of re-working / re-organizing our documentation to find things easier.

### CODE REVIEW

**Review by howardyoo — CHANGES_REQUESTED** [review]
Nice work!
Here are my comments
1. The expand arrow (which arrow) - seems too big and bulky. Can we make it smaller?
2. When clicking the section name, it expands. I think when clicking the expanded section, it should retract and hide its sub-pages. Right now it just refreshes and the animation looks jerky. I think user's expectation may be that the section would be collapsed.
3. The gray hr line when section is expanded, doesn't seem to have too much of a purpose. Perhaps we should just remove it.

**Comment by rreedtd** [comment]
1. I removed the border/background of the expand arrow/caret on click, and replaced that visual feedback by changing the caret color on hover. This should make it feel "smaller"
2. Let's think about this one. Take "Main Features" for example: 
      - This is an actual page, and a link. (this is why it "refreshes" on click) - From any other page, if you click the text, I'd expect to navigate to that "top-level" page...
      - I also agree with you - it makes sense to click the whole bar/area of "Main Features" to expand/collapse the section...... 
      - This poses the question - should collapsible menu items be a page to which we can navigate, or only a button with no actual page? We could add a sub-page like "Overview" or similar, but it would make generating the sidebar menu more challenging
      - For now, I'm disabling the link/href if that happens to be the "current page", forcing you to use the caret button instead to expand/collapse.

3. The grey line was just a visual aid for "what is this page's parent item" - I removed it, see how it flows

**Comment by howardyoo** [comment]
> 1. I removed the border/background of the expand arrow/caret on click, and replaced that visual feedback by changing the caret color on hover. This should make it feel "smaller"
> 2. Let's think about this one. Take "Main Features" for example:
>    
>    * This is an actual page, and a link. (this is why it "refreshes" on click) - From any other page, if you click the text, I'd expect to navigate to that "top-level" page...
>    * I also agree with you - it makes sense to click the whole bar/area of "Main Features" to expand/collapse the section......
>    * This poses the question - should collapsible menu items be a page to which we can navigate, or only a button with no actual page? We could add a sub-page like "Overview" or similar, but it would make generating the sidebar menu more challenging
>    * For now, I'm disabling the link/href if that happens to be the "current page", forcing you to use the caret button instead to expand/collapse.
> 3. The grey line was just a visual aid for "what is this page's parent item" - I removed it, see how it flows

Just checked - way better experience navigating, and there is no confusion now of what to do to expand/collapse the branch.

The arrow still looks too fat to me.
I think you are using this character: ▶︎, but I would suggest perhaps using ▸ .

**Comment by howardyoo** [comment]
I still don't like the fact that the menu expands (or redraws) everytime you click the page. Maybe there might be a way to not do the scrolling animation when the page is first drawing?

**Comment by rreedtd** [comment]
I updated the character for the menu button - on my windows machine, it did not have a border, but here in github, it does show a border. weird. If this still looks off - can you include a pic? I think we're seeing different things. 

This is how it appears to me now: 
image


I disabled the transition for when we programmatically open the menus - in other words, disabled the transition on page load. 
Still looks a bit weird when you get into nested menus, but the greater portion of the menu looks better this way.

**Comment by howardyoo** [comment]
Yes, I agree. it’s not 100%, but still better than before.
We can think about enhancing that in the future, perhaps. I’m satisfied with what it is.

**Comment by howardyoo** [comment]
> I updated the character for the menu button - on my windows machine, it did not have a border, but here in github, it does show a border. weird. If this still looks off - can you include a pic? I think we're seeing different things.
> 
> This is how it appears to me now: image
> 
> I disabled the transition for when we programmatically open the menus - in other words, disabled the transition on page load. Still looks a bit weird when you get into nested menus, but the greater portion of the menu looks better this way.

Looks good to me (chrome)
image

**Review by howardyoo — APPROVED** [review]
LTGM. Thank you for making these changes!

**Comment by howardyoo** [comment]
image

**Pull request merged**
